---
user_role_map:
  HCA: hal
  Nurse: nasir
  Doctor: dale
database: nhclinical
user: admin
password: changeme
server: "http://127.0.0.1:8069"
urls:
  login: "/mobile/login"
  mobile_login: "/mobile/login"
  desktop_login: "/web/login"
