---
user_role_map:
  HCA: hal
  Nurse: nasir
  Doctor: dale
database: nhclinical
server: "http://localhost:8069"
urls:
  login: "/mobile/login"
  mobile_login: "/mobile/login"
  desktop_login: "/web/login"
